[tool.poetry]
name = "argolid_container"
version = "0.1.0"
description = ""
authors = []
packages = [{include = "container", from = "."}]


[tool.poetry.dependencies]
python = "^3.9"
argolid = "0.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
